### ISSUE TITLE
不支持Wilddog Sync

### ISSUE THREAD

**Issue by vaanxy** [WildDogTeam/wilddog-egret#1]
可否更新下这个d.ts文件，
似乎不支持Wilddog Sync

**Comment by stackOverMind** [comment]
新版正在测试中

**Comment by stackOverMind** [comment]
@vaanxy 现在已经支持

**Comment by vaanxy** [comment]
谢谢啦，这个项目不知道能不能添加到npm中如 @types/wilddog 方便使用ts的开发者们～

**Comment by stackOverMind** [comment]
@vaanxy 在2.3.9的npm包中是有的，事实上这个项目中的.d.ts 就是从npm包中拿出来的

**Comment by vaanxy** [comment]
测试OK，非常感谢！
